ENV_PARAMS = [
    {
        # Test_0
        "n_agents": 7,
        "x_dim": 30,
        "y_dim": 30,
        "n_cities": 2,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 0,
        "seed": 0,
    },
    { 
        # Test_1
        "n_agents": 10,
        "x_dim": 30,
        "y_dim": 30,
        "n_cities": 2,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 100,
        "seed": 0,
    },
    {
        # Test_2
        "n_agents": 20,
        "x_dim": 30,
        "y_dim": 30,
        "n_cities": 3,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_3
        "n_agents": 50,
        "x_dim": 30,
        "y_dim": 35,
        "n_cities": 3,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_4
        "n_agents": 80,
        "x_dim": 35,
        "y_dim": 30,
        "n_cities": 5,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_5
        "n_agents": 80,
        "x_dim": 45,
        "y_dim": 35,
        "n_cities": 7,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_6
        "n_agents": 80,
        "x_dim": 40,
        "y_dim": 60,
        "n_cities": 9,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_7
        "n_agents": 80,
        "x_dim": 60,
        "y_dim": 40,
        "n_cities": 13,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_8
        "n_agents": 80,
        "x_dim": 60,
        "y_dim": 60,
        "n_cities": 17,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_9
        "n_agents": 100,
        "x_dim": 80,
        "y_dim": 120,
        "n_cities": 21,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_10
        "n_agents": 100,
        "x_dim": 100,
        "y_dim": 80,
        "n_cities": 25,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_11
        "n_agents": 200,
        "x_dim": 100,
        "y_dim": 100,
        "n_cities": 29,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_12
        "n_agents": 200,
        "x_dim": 150,
        "y_dim": 150,
        "n_cities": 33,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_13
        "n_agents": 400,
        "x_dim": 150,
        "y_dim": 150,
        "n_cities": 37,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
    {
        # Test_14
        "n_agents": 425,
        "x_dim": 158,
        "y_dim": 158,
        "n_cities": 41,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1 / 200,
        "seed": 0,
    },
     {
        # Test_15, similar to Test_0 but with 1/200 malfunction rate
        "n_agents": 7,
        "x_dim": 30,
        "y_dim": 30,
        "n_cities": 2,
        "max_rails_between_cities": 2,
        "max_rail_pairs_in_city": 2,
        "malfunction_rate": 1/200,
        "seed": 0,
    },
]
